name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 3.0.0-dev
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cryptography: ^2.5.0
  hive:
    git:
      url: https://github.com/wufd/hive.git
      path: hive
      ref: master
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.4
  lints: ">=1.0.0"
  mockito: ^5.4.2
  build_runner: ^2.4.6
