name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 3.0.0-dev
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  hive:
    git:
      url: https://github.com/wufd/hive.git
      path: hive
      ref: master
  analyzer: ">=4.6.0 <7.0.0"
  source_helper: ^1.3.4

dev_dependencies:
  test: ^1.24.4
  build_test: any
  build_runner: any
  pedantic: ^1.11.1
